#12 user login and registration
boolean-uk/team-dev-client-c12 pull request #35
Opened 2024-07-17 17:20 UTC by Hamada-AB

2024-07-18 08:42 UTC, FBagdeli submitted a review, later dismissed

2024-07-18 10:53 UTC, vherus requested changes

2024-07-18 10:53 UTC, vherus commented on src/context/auth.js
> +    localStorage.setItem("token", token); // Isn't it redundant, as the token is already stored in localStorage during login or registration?
It might well be. You can either test it and remove this if it is redundant, or remove the comment and leave the code in

2024-07-18 10:53 UTC, vherus commented on src/service/apiClient.js
> +  if (res.data.error) return res;
Let's stick with `{ }` code blocks to keep things readable and consistent with the rest of the codebase

2024-07-18 11:49 UTC, vherus requested changes

2024-07-18 11:49 UTC, vherus commented on src/components/form/textInput/index.js
> +<<<<<<< HEAD
You'll need to remove this. Did you run & test the app before resubmitting for review?

2024-07-18 11:49 UTC, vherus commented on src/components/form/textInput/index.js
> +=======
This needs to go as well

2024-07-18 11:49 UTC, vherus commented on src/components/form/textInput/index.js
> +>>>>>>> main
and this

2024-07-18 11:49 UTC, vherus commented on src/styles/_form.css
> +=======
and this

2024-07-18 11:49 UTC, vherus commented on src/styles/_form.css
> +<<<<<<< HEAD
and this

2024-07-18 11:49 UTC, vherus commented on src/styles/_form.css
> +>>>>>>> main
and this

2024-07-18 16:13 UTC, LeonardoSaraceli approved these changes

2024-07-19 10:08 UTC, vherus requested changes

2024-07-19 10:08 UTC, vherus commented on src/components/posts/index.js
> +  console.log(posts);
Let's remove the debug log

2024-07-19 10:16 UTC, Hamada-AB commented on src/components/posts/index.js
> +  console.log(posts);
done

2024-07-19 10:19 UTC, vherus approved these changes

2024-07-19 10:25 UTC, LeonardoSaraceli approved these changes

2024-07-19 10:26 UTC, merged