fix: required first and last names at create profile and remove back …
boolean-uk/team-dev-client-c12 pull request #48
Opened 2024-07-18 16:05 UTC by LeonardoSaraceli

…btn from step one

2024-07-18 16:14 UTC, Hamada-AB submitted a review, later dismissed

2024-07-19 08:41 UTC, FBagdeli approved these changes

2024-07-19 09:08 UTC, vherus requested changes

2024-07-19 09:08 UTC, vherus commented on src/components/stepper/index.js
> +        if (data.firstName.length === 0 || data.lastName.length === 0) {
This `Stepper` is a generic component that shouldn't care about the specific data being passed in to it. This line of code is tightly coupling it to the data, removing it's use as a general reusable component. You'll need to figure out a different approach to keep this component general use

2024-07-19 09:49 UTC, vherus requested changes

2024-07-19 09:49 UTC, vherus commented on src/components/stepper/index.js
> +const Stepper = ({ header, children, onComplete, missingFields }) => {
This is a step in the right direction but what may be even better is a simple `canProgress` boolean prop.

```js
const canProgress = profile.firstName.length !== 0 && profile.lastName.length !== 0

<Stepper header={<WelcomeHeader />} onComplete={onComplete} canProgress={canProgress}>
```

2024-07-19 09:49 UTC, vherus commented on src/components/stepper/index.js
> +        if (missingFields()) {
Based on the above, you can then just do

```js
if (!canProgress) {
  return
}
```

2024-07-19 10:32 UTC, vherus submitted a review, later dismissed

2024-07-19 11:02 UTC, Hamada-AB approved these changes

2024-07-19 11:04 UTC, FBagdeli approved these changes

2024-07-19 11:09 UTC, merged