#79 Fix hardcoded User details
boolean-uk/team-dev-client-c12 pull request #83
Opened 2024-07-22 14:01 UTC by angustownsley

Also includes a change making all initials capitalised

2024-07-22 14:11 UTC, MyrtheDullaart submitted a review, later dismissed

2024-07-22 14:14 UTC, LeonardoSaraceli approved these changes

2024-07-22 14:32 UTC, vherus requested changes

2024-07-22 14:32 UTC, vherus commented on src/context/currentUser.js
> +                    : setCurrentUser({ empty: true })
Why are you using 2 different models in the same state instead of `null`?

2024-07-22 14:32 UTC, vherus commented on src/context/currentUser.js
> +            )
I can't let you get away with these ternarys, you fiend. Worst case, use readable if statements instead. Not sure if this is a side-effect of having this `user.empty` thing I touched on above.

Additionally, is all of this state really necessary? Why not just store the `user` object in the Auth context provider so all of this data is available and the relevant components can just use that data? You get the user object in the response that contains the token, so you'd only need to make a second fetch to get the users details if they're loading a token from localStorage and there is no user currently in state

2024-07-22 14:32 UTC, vherus commented on src/context/currentUser.js
> +            )
Do we need to keep the user's initials in state? If the app has access to the user's first and last name, it's safer to just run the uppercase on the first letter of each name when needed, if it's in state then you have another point in the app which could trigger re-renders or become stale

2024-07-22 16:55 UTC, Auenc commented on src/components/createPostModal/index.jsx
> +    const userInitials =
Can we refactor this to not have so many `ors`? 

We only won't have a `currentUser` firstname/last name if the user isn't logged in - if the user isn't logged in, they shouldn't be able to make a post anyway. So instead, do a guard check on `firstName` and `lastName`, if they don't exist, error / navigate to login page

2024-07-22 16:57 UTC, Auenc requested changes

2024-07-22 16:57 UTC, Auenc commented on src/components/createPostModal/index.jsx
> +                    classes={`${text.length ? 'blue' : 'offwhite'} width-full`}
let's put this into it's own variable before the return

2024-07-22 16:57 UTC, Auenc commented on src/components/editPostModal/index.jsx
> +    const userInitials =
We're repeating ourselves here. Consider splitting this into a component. In either case, still remove the amount of `||`

2024-07-22 16:57 UTC, Auenc commented on src/components/editPostModal/index.jsx
> +                    classes={`${text.length ? 'blue' : 'offwhite'} width-full`}
this is also a repeat, can we get this into a component?

2024-07-22 16:57 UTC, Auenc commented on src/components/header/index.jsx
> +        `${currentUser?.firstName || ''} ${currentUser?.lastName || ''}` || ''
same as above, this is very similar code

2024-07-23 08:53 UTC, LeonardoSaraceli submitted a review, later dismissed

2024-07-23 09:01 UTC, vherus requested changes
This is a big improvement, good work. A couple of more notes

2024-07-23 09:01 UTC, vherus commented on src/context/currentUser.jsx
> +export const CurrentUserProvider = ({ children }) => {
The problem is that now you have a `user` stored in the AuthContext, and a separate user object stored in this context. I'd probably just get rid of this context and move things over to the auth context instead

2024-07-23 09:34 UTC, vherus approved these changes

2024-07-23 09:44 UTC, PerikK approved these changes

2024-07-23 09:50 UTC, merged