#81 prevent login redirect during profile creation after refresh
boolean-uk/team-dev-client-c12 pull request #85
Opened 2024-07-22 16:33 UTC by Hamada-AB

2024-07-22 16:59 UTC, angustownsley approved these changes

2024-07-22 17:00 UTC, MyrtheDullaart approved these changes

2024-07-22 17:04 UTC, Auenc requested changes

2024-07-22 17:04 UTC, Auenc commented on src/context/auth.jsx
> +      } else {
if you `return` in the if statement, we can remove this else

2024-07-22 17:04 UTC, Auenc commented on src/context/auth.jsx
> +      } else {
same as above, if we add a `return` to the if statement, we don't need the `else`

2024-07-22 17:04 UTC, Auenc commented on src/context/auth.jsx
> +      } else {
same as above

2024-07-23 13:57 UTC, Auenc approved these changes

2024-07-23 14:47 UTC, LeonardoSaraceli approved these changes

2024-07-23 14:48 UTC, merged